---
apiVersion: v1
kind: Namespace
metadata:
  name: jmeter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter
  labels:
    name: jmeter
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jmeter
  template:
    metadata:
      labels:
        name: jmeter
    spec:
      containers:
      - name: jmeter
        image: justb4/jmeter
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: jmeter
  namespace: jmeter
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: jmeter